FORMAT: 1A
HOST: http://patientos.ep.dev.pos/api


# Scratchbook
TODO

# Group Application
Notes related resources of the **Application API**


## Archived ordersets [/ordersets/archives]
### Gets a list of archived ordersets. [GET]

+ Parameters
    + search_term (optional, string) ... Filter by partial string match based on any of the following: last name, 'last_name, first_name', date of birth, MRN, and insurance number.
The partial matching can start at any position in the string. (eg. "ith" matches "Smith")
    + dob (optional, string) ... Filter by the patient's date of birth, using the format yyyy-mm-dd. (eg. 2013-07-30)
    + first_name (optional, string) ... Filter by the patient's first name. Must match the entire string.
    + hcn (optional, string) ... Filter by the patient's Health Care Number (insurance number). Must match the entire string.
    + last_name (optional, string) ... Filter by the patient's last name. Must match the entire string.
    + location (optional, string) ... Filter by the patient's location based on the encounters location field.
    + mrn (optional, string) ... Filter by the patient's Medical Record Number. Must match the entire string.
    + per_page (optional, string) ... Limit the output to a certain number of ADT Patients.
    + page (optional, string) ... The paging offset to start at.
    + unique_patient (optional, string) ... Remove duplicates based on first_name, middle_name, last_name, and mrn
    + _id (optional, string) ... Will return an array of 1 matching that patient id.
    
+ Response 200 (application/json)
        {
            "total": 1557,
            "data":
            [
                {
                    "saved_document_summary":
                    {
                        "id_saved_orderset":"001c2ed9-013b-fec7-6fe4-7f000101aa77",
                        "title":"WSIB REC Multidisciplinary Health Care Assessment Summary Report",
                        "id_local_orderset_info":1005553,
                        "active_version":14,
                        "version":5,
                        "facility_id":null,
                        "id_entrypoint_client":3,
                        "id_entrypoint_user":32,
                        "id_approving_user":null,
                        "id_patient":6555,
                        "patient_number":"MRN3608520232",
                        "state":"Submitted",
                        "draft_ts":"2012-11-14T18:09:46Z",
                        "effective_at":"2012-11-14T18:09:47Z",
                        "visible":"Y",
                        "user_given_name_1":"Fairooz",
                        "user_family_name":"Hussain",
                        "family_name":"Smith",
                        "given_name_1":"Aline",
                        "given_name_2":"Yvonne"
                    }
                },
                {
                    "saved_document_summary":
                    {
                        "id_saved_orderset":"001daaaf-013b-f68b-19d9-7f000101aa77",
                        "title":"WSIB REC Multidisciplinary Health Care Assessment Summary Report",
                        "id_local_orderset_info":1005553,
                        "active_version":14,
                        "version":5,
                        "facility_id":null,
                        "id_entrypoint_client":3,
                        "id_entrypoint_user":32,
                        "id_approving_user":null,
                        "id_patient":6597,
                        "patient_number":"MRN7617850040",
                        "state":"Submitted",
                        "draft_ts":"2012-11-14T18:11:13Z",
                        "effective_at":"2012-11-14T18:11:14Z",
                        "visible":"Y",
                        "user_given_name_1":"Fairooz",
                        "user_family_name":"Hussain",
                        "family_name":"Jones",
                        "given_name_1":"Edmund",
                        "given_name_2":"Ty"
                    }
                }
            ]
        }   

## Draft ordersets [/ordersets/drafts]
### Gets a list of draft ordersets. [GET]

+ Parameter
    + _id (optional, string) ... Will return an array of one that matches that id_saved_orderset
    + entrypoint_user_id (optional, string) ... Filter by the entrypoint_user_id
    + draft_ts_from (optional, string) ... Filter all saved order sets who's draft_ts >= the given value
    + draft_ts_to (optional, string) ... Filter all saved order sets who's draft_ts <= the given value
    + local_document_info_id (optional, string) ... Filter all saved order sets that matches the given local_document_info_id
    + include_total (optional, string) ... Include total when set to 'true'.
    
+ Response 200 (application/json)

        {
            "total": 299,
            "data":
            [
                {
                    "saved_document_summary":
                    {
                        "id_saved_orderset":"001c2ed9-013b-fec7-6fe4-7f000101aa77",
                        "title":"WSIB REC Multidisciplinary Health Care Assessment Summary Report",
                        "id_local_orderset_info":1005553,
                        "active_version":14,
                        "version":5,
                        "facility_id":null,
                        "id_entrypoint_client":3,
                        "id_entrypoint_user":32,
                        "id_approving_user":null,
                        "id_patient":6555,
                        "patient_number":"MRN3608520232",
                        "state":"Draft",
                        "draft_ts":"2012-11-14T18:09:46Z",
                        "effective_at":"2012-11-14T18:09:47Z",
                        "visible":"Y",
                        "user_given_name_1":"Fairooz",
                        "user_family_name":"Hussain",
                        "family_name":"Smith",
                        "given_name_1":"Aline",
                        "given_name_2":"Yvonne"
                    }
                },
                {
                    "saved_document_summary":
                    {
                        "id_saved_orderset":"001daaaf-013b-f68b-19d9-7f000101aa77",
                        "title":"WSIB REC Multidisciplinary Health Care Assessment Summary Report",
                        "id_local_orderset_info":1005553,
                        "active_version":14,
                        "version":5,
                        "facility_id":null,
                        "id_entrypoint_client":3,
                        "id_entrypoint_user":32,
                        "id_approving_user":null,
                        "id_patient":6597,
                        "patient_number":"MRN7617850040",
                        "state":"Draft",
                        "draft_ts":"2012-11-14T18:11:13Z",
                        "effective_at":"2012-11-14T18:11:14Z",
                        "visible":"Y",
                        "user_given_name_1":"Fairooz",
                        "user_family_name":"Hussain",
                        "family_name":"Jones",
                        "given_name_1":"Edmund",
                        "given_name_2":"Ty"
                    }
                }
            ]
        }
        
        
        
# Group Cached Resources   

## Cached Resource Information [/cached_resources/@{saved_orderset_id}/information]
### Information for the cached resource - title and number of pages. (beta) [GET]

+ Parameter
    + saved_orderset_id (string) ... The id of the saved orderset
    
+ Response 200 (application/json)
        
        {
            cached_resource: 
            {
                title: "WSIB REC Multidisciplinary Health Care Assessment Summary Report",
                number_of_pages: 1,
                has_summary_view: false,
                number_of_summary_pages: 1,
                "hypermedia_links": {
                    "pdfUrl": "http://patientos.bw.dev.pos:3000/api/cached_resources/001c2ed9-013b-fec7-6fe4-7f000101aa77/pdf",
                    "imageUrls": [
                        "http://patientos.bw.dev.pos:3000/api/cached_resources/001c2ed9-013b-fec7-6fe4-7f000101aa77/page_image/0"
                    ]
                }
            }
        }

## Cached Resource PDF [/api/cached_resources/@{saved_orderset_id}/pdf]
### PDF of the cached resource. [GET]

+ Parameter
    + saved_orderset_id (string) ... The id of the saved orderset

+ Response 200 (application/pdf)


## Cached Resource PDF [/api/cached_resources/@{saved_orderset_id}/page_image/{page_number}]
### PDF of the cached resource. [GET]

+ Parameter
    + saved_orderset_id (string) ... The id of the saved orderset
    + page_number (string) ... The page number. You need to retrieve one page image agt a time.

+ Response 200 (application/png)
        
        

# Group Associated Documents   

## Associated Documents [/associated_documents]
### Gets a list of associated documents. [GET]

+ Parameter
    + legacy_tx_id (string) ... The id of the document (i.e. /api/documents/search output returned id)
    
+ Response 200 (application/json)

        {
            "data":
            [
                {
                    "associated_document":
                    {
                        "title":"Bowel Care Clinical Protocol",
                        "docType":"Clinical Protocol",
                        "id":54,
                        "hypermedia_links":
                        {
                            "imageUrls":
                            [
                                "http://patientos.aw.dev.pos:3000/api/associated_documents/54/page/1.png",
                                "http://patientos.aw.dev.pos:3000/api/associated_documents/54/page/2.png"
                            ],
                            "pdfUrl":"http://patientos.aw.dev.pos:3000/api/associated_documents/54.pdf"
                        }
                    }
                },
                {
                    "associated_document":
                    {
                        "title":"Hypoglycemia Management Clinical Protocol",
                        "docType":"Clinical Protocol",
                        "id":55,
                        "hypermedia_links":
                        {
                            "imageUrls":
                            [
                                "http://patientos.aw.dev.pos:3000/api/associated_documents/55/page/1.png",
                                "http://patientos.aw.dev.pos:3000/api/associated_documents/55/page/2.png"
                            ],
                            "pdfUrl":"http://patientos.aw.dev.pos:3000/api/associated_documents/55.pdf"
                        }
                    }
                }
            ]
        }